name: Update Stats.fm Albums

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  update-albums:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Stats.fm to Markdown
        uses: cow279/statsfm-to-markdown@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
